spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lab2db
    username: app
    password: app

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        formal-sql: true
        default_schema: lab2

  springdoc:
    swagger-ui:
      path: /swagger-ui.html

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE
